# Generated by Django 2.2 on 2020-08-28 03:22

import account.model_addon
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('topic', models.CharField(choices=[('1', 'Computer Science'), ('2', 'Medical'), ('3', 'Marketing'), ('4', 'Business'), ('5', 'Sport'), ('6', 'Places'), ('7', 'Development'), ('8', 'Other')], max_length=255, verbose_name='Topic')),
                ('description', models.TextField()),
                ('image', stdimage.models.StdImageField(blank=True, default='default/img/idea.png', null=True, upload_to=account.model_addon.UploadToPathAndRename('upload/img/idea'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), stdimage.validators.MinSizeValidator(200, 200), stdimage.validators.MaxSizeValidator(1200, 1200)], verbose_name='Image')),
                ('file', models.FileField(blank=True, null=True, upload_to=account.model_addon.UploadToPathAndRename('upload/file/resume'), validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Resume')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'idea',
                'verbose_name_plural': 'ideas',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='idea.Idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
