# Generated by Django 2.2 on 2020-08-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamaccount',
            name='work_tag',
            field=models.IntegerField(choices=[('1', 'Front End'), ('2', 'Back End'), ('3', 'Full Stack'), ('4', 'Designer'), ('5', 'Leader')], max_length=255, verbose_name='Work Tag'),
        ),
    ]
