# Generated by Django 3.0.8 on 2020-07-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en-us', 'English'), ('ar', 'Arabic')], default='en-us', max_length=5)),
            ],
        ),
    ]
