# Generated by Django 3.0.8 on 2020-08-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsetting',
            options={'verbose_name': 'global setting', 'verbose_name_plural': 'global setting'},
        ),
    ]
